services:
  - type: web
    name: nexora
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: EXPERIENTIAL_API_KEY
        sync: false
